from django.conf.urls import url, include, i18n
from myrobogals.rgforums import views as rgforums_views

urlpatterns = [
    url(r'^newcategory/$', rgforums_views.newcategory),
    url(r'^newforum/$', rgforums_views.newforum),
    url(r'^stickytopic/$', rgforums_views.stickytopic),
    url(r'^setmaxuploadfilesize/$', rgforums_views.setmaxuploadfilesize),
    url(r'^category/delete/(?P<category_id>\d+)/$', rgforums_views.deletecategory),
    url(r'^forum/delete/(?P<forum_id>\d+)/$', rgforums_views.deleteforum),
    url(r'^topic/delete/(?P<topic_id>\d+)/$', rgforums_views.deletetopic),
    url(r'^post/delete/(?P<post_id>\d+)/$', rgforums_views.deletepost),
    url(r'^post/fileoffenses/(?P<post_id>\d+)/$', rgforums_views.fileoffenses),
    url(r'^showforumoffenses/(?P<forum_id>\d+)/$', rgforums_views.showforumoffenses),
    url(r'^unwatchforum/(?P<forum_id>\d+)/$', rgforums_views.unwatchforum),
    url(r'^watchforum/(?P<forum_id>\d+)/$', rgforums_views.watchforum),
    url(r'^unwatchtopic/(?P<topic_id>\d+)/$', rgforums_views.unwatchtopic),
    url(r'^watchtopic/(?P<topic_id>\d+)/$', rgforums_views.watchtopic),
    url(r'^unwatchalltopics/$', rgforums_views.unwatchalltopics),
    url(r'^watchmytopics/$', rgforums_views.watchtopicwithmyposts),
    url(r'^unwatchall/(?P<uidb36>.+)/(?P<token>.+)/(?P<step>\d)/$', rgforums_views.unwatchall),
    url(r'^search/(?P<chapterurl>.+)/$', rgforums_views.search),
    url(r'^newtopic/(?P<forum_id>\d+)/$', rgforums_views.newtopic),
    url(r'^newpost/(?P<topic_id>\d+)/$', rgforums_views.newpost),
    url(r'^editpost/(?P<post_id>\d+)/$', rgforums_views.editpost),
    url(r'^upvote/(?P<post_id>\d+)/$', rgforums_views.topicupvote),
    url(r'^undoupvote/(?P<post_id>\d+)/$', rgforums_views.topicundoupvote),
    url(r'^deletefile/(?P<post_id>\d+)/(?P<file_id>\d+)/$', rgforums_views.deletefile),
    url(r'^downloadpostfile/(?P<post_id>\d+)/(?P<file_id>\d+)/$', rgforums_views.downloadpostfile),
    url(r'^editforum/(?P<forum_id>\d+)/$', rgforums_views.editforum),
    url(r'^topic/(?P<topic_id>\d+)/$', rgforums_views.viewtopic),
    url(r'^forum/(?P<forum_id>\d+)/$', rgforums_views.viewforum),
    url(r'^$', rgforums_views.forums),
    url(r'^(?P<forum_id>\d+)/blacklistuser/(?P<user_id>\d+)/$', rgforums_views.blacklistuser),
    url(r'^(?P<forum_id>\d+)/unblacklistuser/(?P<user_id>\d+)/$', rgforums_views.unblacklistuser)
]
